apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: watch-marketplace
data:
  DB_HOST: "mysql-service"
  DB_NAME: "watch_store"
  DB_USER: "root"
  DB_PASS: "root"
  S3_ENDPOINT: "http://localstack.watch-marketplace.svc.cluster.local:4566"
